dist: trusty
sudo: false
language: node_js
node_js: 8.6.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
cache:
  yarn: true
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: rtsao@uber.com
  api_key:
    secure: o6aaMNtGQ+7haCgt3THBmZ4GubV6OcyIb/dzPV4ysmjKn1HKJEUj57T0btYh4Vm630RhHKoGmRiZMK4qfaLetnxMy0cxZRYW8C/AwPMOiqXlf5t3o9uC32uL+9ewU+YBtRkhSSf6p4bD+RKWZTNE7y4Us4Ux8zGxQWm4r/n6H0AL4aPpE9HcNzETnZZHXcpCryGypBhPPVGQNX197Padxk8HLPMKukNtsIT8h+15xDDBUg25kYYwJpIHcAT5gGBUX4OcknY4DBPcCAtxvNKVQ8iKOfUMJ2byufgWtRIMp3iHkMMzYa0XYePnIVV56O0xt4LODj/xNTooWwp70Nz+joirGazS1MQkwA+oDbl1hHP7wtsrekPSlEDFmhbMXk526vZP8E211mByYLaTJKjOIgCdBmWh3k7edwN5wb9BYlq26NdDD5XMmoyV5Tq+ExN7FyBE5gDnErvk62Xdcekd7Zvod8PpoBchBK2Z4UkBVd/MoWpOShypp2SUcXvnTFi37Nty9k/KyXB+tiZTc1kKHlVVpeZ1SzaQayaP90iaPoN8asHBEEO0q1yDhjwhTTvmNSD3EJSxY7VoT/GaYkPTyIb4IU3Qd6iA/99ENZpAj6Z3GhsJC0Fj51/+//Ap9wjtpgPuk34Q3TY3Sw5u8junEysSJvkXX/iK5sdDvhvkWBs=
  on:
    tags: true
    repo: uber-web/probot-app-label-release-pr
